In [1]:
#1. Python Program to calculate Mean, Median, Mode, Variance and Standard Deviation
import statistics
import math
numbers = list(map(int, input("Enter numbers separated by space: ").split()))
mean = statistics.mean(numbers)
median = statistics.median(numbers)
mode = statistics.mode(numbers)
variance = statistics.variance(numbers)
std_dev = statistics.stdev(numbers)
print("Mean =", mean)
print("Median =", median)
print("Mode =", mode)
print("Variance =", variance)
print("Standard Deviation =", std_dev)

Enter numbers separated by space: 54 55 56 57
Mean = 55.5
Median = 55.5
Mode = 54
Variance = 1.6666666666666667
Standard Deviation = 1.2909944487358056


In [2]:
#2. NumPy Array Operations
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
reshaped = arr.reshape(2, 3)
print("Reshaped Array:\n", reshaped)
print("Element-wise Multiplication:\n", arr * 2)

Sum: 21
Mean: 3.5
Max: 6
Min: 1
Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Element-wise Multiplication:
 [ 2  4  6  8 10 12]


In [3]:
#3. Matrix Operations
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Addition:\n", A + B)
print("Subtraction:\n", A - B)
print("Multiplication:\n", np.matmul(A, B))
print("Transpose of A:\n", A.T)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]


In [4]:
#4. Random Array Statistics
import numpy as np
arr = np.random.randint(1, 100, 10)
print("Array:", arr)
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))

Array: [52 31 89 87 88  5 90  6  6 12]
Mean: 46.6
Standard Deviation: 36.775535346205366
Minimum: 5
Maximum: 90


In [5]:
#5. SciPy Statistics and t-test
import numpy as np
from scipy import stats
data = [10, 12, 9, 11, 10, 13, 12]
mean = stats.tmean(data)
print("Mean using scipy:", mean)
t_stat, p_value = stats.ttest_1samp(data, 10)
print("T-statistic:", t_stat)
print("P-value:", p_value)

Mean using scipy: 11.0
T-statistic: 1.8708286933869707
P-value: 0.1105517404022668


In [8]:
#6. Definite Integration using SciPy
from scipy import integrate
def func(x):
    return x**2
result, error = integrate.quad(func, 0, 3)
print("Definite Integration Result:", result)

Definite Integration Result: 9.000000000000002


In [11]:
#7. Function Minimization using SciPy
from scipy import optimize
def func(x):
  return x**2 + 5*x + 6

result = optimize.minimize(func, x0=0)
print("Minimum Value:", result.fun)
print("At x =", result.x)

Minimum Value: -0.2499999999999991
At x = [-2.50000002]
